### ISSUE TITLE
TypeError in GeneralStepDefs this.currentPage[field].clear is not a function

### ISSUE THREAD

**Issue by thoughtcroft** [ReadyTalk/cukefarm#37]
I am pretty new at this but followed the example to test invalid login to our web app. I set up a page object following the guide:

```
var LoginPage = function LoginPage(){

  this.usernameField = by.name('Username');
  this.passwordField = by.name('Password');
  this.loginButton = $('button.btn');

  this.get = function() {
    return browser.get('https://app.zunos.com/#/account/login')
  }

  this.waitForLoaded = function() {
    return browser.wait((function(_this) {
      return function() {
        return _this.loginButton.isPresent();
      };
    })(this), 30000);
  };
}

module.exports = {
  "class": LoginPage,
  name: 'Login'
};
```

The feature uses the General Step definition style but when I run protractor, I get the following output:

```
[13:24:28] I/local - Starting selenium standalone server...
[13:24:28] I/launcher - Running 1 instances of WebDriver
[13:24:29] I/local - Selenium standalone server started at http://192.168.1.226:55201/wd/hub
{ Login: [Function: LoginPage] }
Feature: Login Page

  As a user of Zunos
  I should be able to login
  So that I can access content

  Scenario: Invalid credentials
    Given I am on the "Login" page
    When I type "Foo" in the "Username" field
    And I type "Bar" in the "Password" field
    And I click the "Login" button
    Then I should see the message "Unauthorized"
    And I should see the message "Invalid username or password"

Failures:

1) Scenario: Invalid credentials - features/login_scenarios.feature:6
   Step: When I type "Foo" in the "Username" field - features/login_scenarios.feature:8
   Step Definition: node_modules/cukefarm/lib/step_definitions/GeneralStepDefs.js:19
   Message:
     TypeError: this.currentPage[field].clear is not a function
         at World.<anonymous> (/Users/warrenbain/Projects/aris/arisapp-server/Zunos.WebApp/node_modules/cukefarm/lib/step_definitions/GeneralStepDefs.js:22:31)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9)
````
Any clues as to why this would be happening?

**Comment by thoughtcroft** [comment]
OK, excuse the n00b error. I re-read the protractor documentation and I was only returning the locator and not the element. For example, the 'Username' field should be
```
this.usernameField = element(by.name('Username'));
```
and suddenly it works!
